- name: lfs-cross-toolchain
  hosts: lfs_host
  become_user: lfs
  become: true

  vars_files:
    - vars/tools.yml
  vars:
    lfs_folder: /mnt/lfs
    lfs_target: x86_64-lfs-linux-gnu
    source_folder: '{{ lfs_folder }}/sources'
    compile_jobs: 8
  environment:
    LFS: '{{ lfs_folder }}'
    LC_ALL: POSIX
    LFS_TGT: '{{ lfs_target }}'
    PATH: '{{ lfs_folder }}/tools/bin:/usr/bin'
    CONFIG_SITE: '{{ lfs_folder }}/usr/share/config.site'

  tasks:
    - name: download and compile binutils
      include_tasks: tasks/download_and_compile.yml
      vars:
        url: '{{ tools.binutils.url }}'
        tool_folder: '{{ source_folder }}/{{ tools.binutils.folder }}'
        configure: >
          ../configure --prefix=$LFS/tools \
                       --with-sysroot=$LFS \
                       --target=$LFS_TGT   \
                       --disable-nls       \
                       --enable-gprofng=no \
                       --disable-werror

    - name: download gcc and dependencies
      unarchive:
        src: '{{ item.url }}'
        dest: '{{ source_folder }}'
        creates: "{{ source_folder }}/{{ item.folder }}"
        remote_src: yes
      loop:
        - '{{ tools.gcc }}'
        - '{{ tools.mpfr }}'
        - '{{ tools.gmp }}'
        - '{{ tools.mpc }}'

    - name: link gcc dependencies
      file:
        src: '{{ source_folder }}/{{ item.value.folder }}'
        dest: '{{ source_folder }}/{{ tools.gcc.folder }}/{{ item.name }}'
        state: link
      loop:
        - { name: mpfr, value: '{{ tools.mpfr }}' }
        - { name: gmp, value: '{{ tools.gmp }}' }
        - { name: mpc, value: '{{ tools.mpc }}' }

    - name: gcc pre install config
      shell: |
        case $(uname -m) in
          x86_64)
            sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
          ;;
        esac
      args:
        chdir: '{{ source_folder }}/{{ tools.gcc.folder }}'

    - name: build gcc
      vars:
        build_folder: '{{ source_folder }}/{{ tools.gcc.folder }}/build'
      block:
      - name: create build folder
        file:
          path: '{{ build_folder }}'
          state: directory

      - name: configure gcc
        shell: |
          ../configure                  \
              --target=$LFS_TGT         \
              --prefix=$LFS/tools       \
              --with-glibc-version=2.36 \
              --with-sysroot=$LFS       \
              --with-newlib             \
              --without-headers         \
              --enable-default-pie      \
              --enable-default-ssp      \
              --disable-nls             \
              --disable-shared          \
              --disable-multilib        \
              --disable-decimal-float   \
              --disable-threads         \
              --disable-libatomic       \
              --disable-libgomp         \
              --disable-libquadmath     \
              --disable-libssp          \
              --disable-libvtv          \
              --disable-libstdcxx       \
              --enable-languages=c,c++
        args:
          chdir: '{{ build_folder }}'

      - name: compile gcc
        shell: make -j {{ compile_jobs }}
        args:
          creates: '{{ build_folder }}/{{ lfs_target }}/libgcc'
          chdir: '{{ build_folder }}'

      - name: install gcc
        shell: make install
        args:
          chdir: '{{ build_folder }}'
          creates: '{{ lfs_folder }}/tools/bin/{{ lfs_target }}-gcc'

    - name: fix gcc headers
      shell: |
          cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
            `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/install-tools/include/limits.h
      args:
        chdir: '{{ source_folder }}/{{ tools.gcc.folder }}'

    - name: install linux headers
      vars:
        folder: "{{ source_folder }}/{{ tools.linux.folder }}"
      block:
        - name: download linux headers
          unarchive:
            src: '{{ tools.linux.url }}'
            dest: '{{ source_folder }}'
            creates: "{{ source_folder }}/{{ tools.linux.folder }}"
            remote_src: yes

        - name: clean headers
          shell: make mrproper
          args:
            chdir: '{{ folder }}'

        - name: install headers
          shell: |
            make headers
            find usr/include -type f ! -name '*.h' -delete
            cp -rv usr/include $LFS/usr
          args:
            chdir: '{{ folder }}'


