- name: lfs
  hosts: lfs_host
  vars:
    lfs_dir: /mnt/lfs
  vars_files:
    - versions.yml
  become: yes
  tasks:
    - name: Create lfs group
      group:
        name: lfs
        state: present
    - name: Create lfs user
      user:
        name: lfs
        group: lfs
        password: "{{ 'ansible' | password_hash('sha512', 'mysecretsalt') }}"
        shell: /bin/bash
        create_home: yes
        skeleton: /dev/null
    - name: set lfs ownership
      file:
        path: '{{ lfs_dir }}'
        state: touch
        mode: '0755'
        owner: lfs
        group: lfs
    - name: Create filesystem
      file:
        path: '{{ lfs_dir }}/{{ item }}'
        state: directory
        mode: '0755'
        owner: lfs
        group: lfs
      loop:
        - sources
        - etc
        - var
        - usr/bin
        - usr/lib
        - usr/lib64
        - usr/sbin
        - tools
