---

- name: download and extract package
  unarchive:
    src: '{{ url }}'
    dest: '{{ source_folder }}'
    creates: '{{ tool_folder }}'
    remote_src: yes

- name: apply patches
  ansible.posix.patch:
    basedir: '{{ tool_folder }}'
    remote_src: yes
    src: '{{ item }}'
  loop: '{{ patch_files }}'
  when: patch_files is defined

- name: create build folder
  file:
    path: '{{ tool_folder }}/build'
    state: directory

- name: preconfigure
  shell: '{{ preconfigure }}'
  when: preconfigure is defined

- name: configure
  shell: '{{ configure }}'
  args:
    chdir: '{{ tool_folder }}/build'
    creates: config.status

- name: compile
  shell: make -j
  args:
    chdir: '{{ tool_folder }}/build'

- name: install
  shell: make install
  args:
    chdir: '{{ tool_folder }}/build'
